name = "comic-reader-web"
main = "worker-src/index.ts"
compatibility_date = "2025-07-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[vars]
BACKEND_ORIGIN = "https://comic.26026155.xyz"
